//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.27 at 04:11:08 PM CEST 
//


package com.project.xml.category;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.project.xml.category package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.project.xml.category
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateCategoryRequest }
     * 
     */
    public CreateCategoryRequest createCreateCategoryRequest() {
        return new CreateCategoryRequest();
    }

    /**
     * Create an instance of {@link AuthorizeResponse }
     * 
     */
    public AuthorizeResponse createAuthorizeResponse() {
        return new AuthorizeResponse();
    }

    /**
     * Create an instance of {@link AuthorizeRequest }
     * 
     */
    public AuthorizeRequest createAuthorizeRequest() {
        return new AuthorizeRequest();
    }

    /**
     * Create an instance of {@link GetAllCategoryResponse }
     * 
     */
    public GetAllCategoryResponse createGetAllCategoryResponse() {
        return new GetAllCategoryResponse();
    }

    /**
     * Create an instance of {@link Category }
     * 
     */
    public Category createCategory() {
        return new Category();
    }

    /**
     * Create an instance of {@link DeleteCategoryResponse }
     * 
     */
    public DeleteCategoryResponse createDeleteCategoryResponse() {
        return new DeleteCategoryResponse();
    }

    /**
     * Create an instance of {@link GetAllCategoryRequest }
     * 
     */
    public GetAllCategoryRequest createGetAllCategoryRequest() {
        return new GetAllCategoryRequest();
    }

    /**
     * Create an instance of {@link DeleteCategoryByIdRequest }
     * 
     */
    public DeleteCategoryByIdRequest createDeleteCategoryByIdRequest() {
        return new DeleteCategoryByIdRequest();
    }

    /**
     * Create an instance of {@link CreateCategoryResponse }
     * 
     */
    public CreateCategoryResponse createCreateCategoryResponse() {
        return new CreateCategoryResponse();
    }

    /**
     * Create an instance of {@link GetCategoryByIdRequest }
     * 
     */
    public GetCategoryByIdRequest createGetCategoryByIdRequest() {
        return new GetCategoryByIdRequest();
    }

    /**
     * Create an instance of {@link UpdateCategoryRequest }
     * 
     */
    public UpdateCategoryRequest createUpdateCategoryRequest() {
        return new UpdateCategoryRequest();
    }

    /**
     * Create an instance of {@link GetCategoryResponse }
     * 
     */
    public GetCategoryResponse createGetCategoryResponse() {
        return new GetCategoryResponse();
    }

}
