//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.27 at 04:11:08 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.project.com/xml/category", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.project.xml.category;
