//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.19 at 10:20:30 PM CEST 
//


package com.project.xml.news;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.project.xml.news package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.project.xml.news
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LoadFileRequest }
     */
    public LoadFileRequest createLoadFileRequest() {
        return new LoadFileRequest();
    }

    /**
     * Create an instance of {@link GetAllNewsResponse }
     *
     */
    public GetAllNewsResponse createGetAllNewsResponse() {
        return new GetAllNewsResponse();
    }

    /**
     * Create an instance of {@link CreateNewsResponse }
     *
     */
    public CreateNewsResponse createCreateNewsResponse() {
        return new CreateNewsResponse();
    }

    /**
     * Create an instance of {@link DeleteNewsResponse }
     *
     */
    public DeleteNewsResponse createDeleteNewsResponse() {
        return new DeleteNewsResponse();
    }

    /**
     * Create an instance of {@link DeleteNewsByIdRequest }
     *
     */
    public DeleteNewsByIdRequest createDeleteNewsByIdRequest() {
        return new DeleteNewsByIdRequest();
    }

    /**
     * Create an instance of {@link GetNewsByIdRequest }
     *
     */
    public GetNewsByIdRequest createGetNewsByIdRequest() {
        return new GetNewsByIdRequest();
    }

    /**
     * Create an instance of {@link GetAllNewsRequest }
     *
     */
    public GetAllNewsRequest createGetAllNewsRequest() {
        return new GetAllNewsRequest();
    }

    /**
     * Create an instance of {@link LoadFileResponse }
     *
     */
    public LoadFileResponse createLoadFileResponse() {
        return new LoadFileResponse();
    }

    /**
     * Create an instance of {@link StoreFileRequest }
     */
    public StoreFileRequest createStoreFileRequest() {
        return new StoreFileRequest();
    }

    /**
     * Create an instance of {@link GetNewsResponse }
     *
     */
    public GetNewsResponse createGetNewsResponse() {
        return new GetNewsResponse();
    }

    /**
     * Create an instance of {@link CreateNewsRequest }
     * 
     */
    public CreateNewsRequest createCreateNewsRequest() {
        return new CreateNewsRequest();
    }

}
